sulu_admin:
    forms:
        directories:
            - "%perspeqtive_sulu_action_block_bundle_path%/config/forms"
    lists:
        directories:
            - "%perspeqtive_sulu_action_block_bundle_path%/config/lists"
    resources:
        !php/const PERSPEQTIVE\SuluActionBlockBundle\Entity\ActionBlock::RESOURCE_KEY:
            routes:
                list: 'perspeqtive_sulu_action_block.get_action-blocks'
                detail: 'perspeqtive_sulu_action_block.get_action-block'
