perspeqtive_sulu_action_block_api:
    prefix: /admin/api/action-blocks
    type: rest
    resource: PERSPEQTIVE\SuluActionBlockBundle\Controller\Admin\ActionBlockController
    name_prefix: perspeqtive_sulu_action_block.
