perspeqtive_sulu_action_blocks_api:
    prefix: /admin/api/action-blocks
    type: rest
    resource: PERSPEQTIVE\SuluActionBlocksBundle\Controller\Admin\ActionBlockController
    name_prefix: perspeqtive_sulu_action_block.
