# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
services:

    PERSPEQTIVE\SuluActionBlocksBundle\Repository\ActionBlockRepository:
        class: PERSPEQTIVE\SuluActionBlocksBundle\Repository\ActionBlockRepository
        arguments:
            $registry: '@doctrine'

    PERSPEQTIVE\SuluActionBlocksBundle\Admin\ActionBlockAdmin:
        class: PERSPEQTIVE\SuluActionBlocksBundle\Admin\ActionBlockAdmin
        arguments:
            $viewBuilderFactory: '@sulu_admin.view_builder_factory'
            $securityChecker: '@sulu_security.security_checker'
        tags:
            - { name: sulu.admin }

    PERSPEQTIVE\SuluActionBlocksBundle\Controller\Admin\ActionBlockController:
        class: PERSPEQTIVE\SuluActionBlocksBundle\Controller\Admin\ActionBlockController
        arguments:
            $viewHandler: '@fos_rest.view_handler'
            $listBuilderFactory: '@sulu_core.doctrine_list_builder_factory'
            $fieldDescriptorFactory: '@sulu_core.list_builder.field_descriptor_factory'
            $restHelper: '@sulu_core.rest_helper'
            $actionBlockRepository: '@PERSPEQTIVE\SuluActionBlocksBundle\Repository\ActionBlockRepository'
            $entityManager: '@doctrine.orm.entity_manager'
        tags:
            - { name: controller.service_arguments }

    PERSPEQTIVE\SuluActionBlocksBundle\Registry\ActionRegistry:
        class: PERSPEQTIVE\SuluActionBlocksBundle\Registry\ActionRegistry
        arguments:
            $actions: !tagged_iterator perspeqtive.sulu_action_block.action

    PERSPEQTIVE\SuluActionBlocksBundle\Content\Select\ActionSelect:
        class: PERSPEQTIVE\SuluActionBlocksBundle\Content\Select\ActionSelect
        public: true
        arguments:
            $actionRegistry: '@PERSPEQTIVE\SuluActionBlocksBundle\Registry\ActionRegistry'

    PERSPEQTIVE\SuluActionBlocksBundle\Content\Select\ActionBlockSelect:
        class: PERSPEQTIVE\SuluActionBlocksBundle\Content\Select\ActionBlockSelect
        public: true
        arguments:
            $actionBlockRepository: '@PERSPEQTIVE\SuluActionBlocksBundle\Repository\ActionBlockRepository'

    PERSPEQTIVE\SuluActionBlocksBundle\Twig\RenderActionBlockExtension:
        class: PERSPEQTIVE\SuluActionBlocksBundle\Twig\RenderActionBlockExtension
        arguments:
            $executor: '@PERSPEQTIVE\SuluActionBlocksBundle\Execution\ActionBlockExecutor'
        tags: ['twig.extension']

    PERSPEQTIVE\SuluActionBlocksBundle\Execution\ActionBlockExecutor:
        class: PERSPEQTIVE\SuluActionBlocksBundle\Execution\ActionBlockExecutor
        arguments:
            $actionBlockRepository: '@PERSPEQTIVE\SuluActionBlocksBundle\Repository\ActionBlockRepository'
            $actionRegistry: '@PERSPEQTIVE\SuluActionBlocksBundle\Registry\ActionRegistry'
            $eventDispatcher: '@event_dispatcher'
            $configurationFactory: '@PERSPEQTIVE\SuluActionBlocksBundle\Configuration\ConfigurationFactory'
            $logger: '@monolog.logger.action_block'
            $environment: '%kernel.environment%'

    PERSPEQTIVE\SuluActionBlocksBundle\EventSubscriber\ActionBlockRedirectSubscriber:
        class: PERSPEQTIVE\SuluActionBlocksBundle\EventSubscriber\ActionBlockRedirectSubscriber
        arguments:
            $requestStack: '@request_stack'
        tags:
            - { name: kernel.event_subscriber }

    PERSPEQTIVE\SuluActionBlocksBundle\Configuration\ConfigurationFactory:
        class: PERSPEQTIVE\SuluActionBlocksBundle\Configuration\ConfigurationFactory
        arguments:
            $resolver: '@PERSPEQTIVE\SuluActionBlocksBundle\Configuration\Resolver\Resolver'

    PERSPEQTIVE\SuluActionBlocksBundle\Configuration\Resolver\Resolver:
        class: PERSPEQTIVE\SuluActionBlocksBundle\Configuration\Resolver\Resolver
        arguments:
            $resolvers: !tagged_iterator perspeqtive.sulu_action_block.configuration_type_resolver

    PERSPEQTIVE\SuluActionBlocksBundle\Configuration\Resolver\LinkResolver:
        class: PERSPEQTIVE\SuluActionBlocksBundle\Configuration\Resolver\LinkResolver
        arguments:
            $documentManager: '@sulu_document_manager.document_manager'
            $webspaceManager: '@sulu_core.webspace.webspace_manager'
            $requestStack: '@request_stack'
        tags:
            - { name: perspeqtive.sulu_action_block.configuration_type_resolver }



